### ISSUE TITLE
Recording Won't Start

### ISSUE THREAD

**Issue by rouzbeh84** [wk-j/vscode-screen-recorder#1]
On 

VSCode Version 1.10.2 (1.10.2)
Mac 10.11.6

Tried uninstalling and reinstalling to no avail. 

Any suggestions?

**Comment by wk-j** [comment]
Is there any error in console (Developer tools)?

**Comment by rouzbeh84** [comment]
This is what I get, unfortunately I'm not that familiar with typescript to look into it myself

 ```
extensionHost.ts:282 [Extension Host] Error: Command failed: /Users/mars-pro/.vscode/extensions/wk-j.screen-recorder-0.0.2/node_modules/mac-active-window/swift/ActiveWindow/.build/debug/ActiveWindow 95275
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/mars-pro/.vscode/extensions/wk-j.screen-recorder-0.0.2/node_modules/mac-active-window/swift/ActiveWindow/.build/debug/ActiveWindow
  Reason: image not found

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] rejected promise not handled within 1 second
shell.ts:426 Cannot read property 'x' of undefined: TypeError: Cannot read property 'x' of undefined
    at findActiveWindow.then.rs (/Users/mars-pro/.vscode/extensions/wk-j.screen-recorder-0.0.2/out/src/recorder.js:116:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:426(anonymous function) @ shell.ts:383e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by Expometals** [comment]
same error in windows

**Comment by andythedandyone** [comment]
nothing happens when i click on record button either.. I'm on windows 10

**Comment by codercodingthecode** [comment]
@Expometals , it is currently only supported on MacOS, as stated on project github Readme.
